config/routes.rb
Rails.application.routes.draw do
  resources :users

  match 'role_name_search'         , to: 'roles#role_name_search', :via => :get
  match 'user_roles_search/(:id)'  , to: 'users#user_roles_search', :via => :get

  root 'users#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles

  def last_name
    # how to query:  j = User.first.to_json :methods => :last_name
    return "" if name.nil?
    name.split(" ").last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def role_name_search
    if params[:term].present?
      @roles = Role.where( "roles.name like ?", "%#{params[:term]}%" )
      render json: @roles
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def user_roles_search
    result = []
    y = {}
    if params[:id].present?
      #role_ids = User.find(params[:id]).roles.map{ |e| [e.id, e.name] }
      User.find(params[:id]).roles.each { |r| y[:id] = r.id; y[:text] = r.name; result << y; y = {} }
    else
      Role.all.each { |r| y[:id] = r.id; y[:text] = r.name; result << y; y = {} }
      #Role.all.where( "id = ?",  params[:id] ).each { |r| y[:id] = r.id; y[:text] = r.name; result << y; y = {} }
    end
    #render json: [{id:1,text:'secretary'},{id:2,text:'key_user'}]
    render json: result
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    p = params[:role_ids][0].gsub("-,","").gsub("-","")
    #@user = User.new( user_params.merge( "role_ids" => params[ :role_ids ][0].split(",") ) )
    @user = User.new( user_params.merge( "role_ids" => p.split(",") ) )
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      #require 'pry'; binding.pry
      #@user = User.new( user_params.merge( "role_ids" => params[ :role_ids ][0].split(",") ) )
      #if params[:role_ids][0].include? ","
      #  p = params[:role_ids][0].slice(params[:role_ids][0].index(",")+1..-1)
      #  p = p.split(",")
      #else
      #  p = []
      #end
      p = params[:role_ids][0].gsub("-,","").gsub("-","")
      if @user.update(user_params.merge( "role_ids" => p.split(",") ) )
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, role_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>RailsAutocompleteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/old2_application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>RailsAutocompleteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    $(document).on('page:change', function() {
      $("#e11").select2({
        placeholder: "pesquisa...",
        minimumInputLength: 2,
        multiple: true,
        width: "300px",
        ajax: {
          url: "<%= user_name_search_path(format: 'json') %>",
          dataType: "json",
          data: function (term) {
            return {
              term: term
            };
          },
          results: function (data) {
            return {
              results: $.map(data, function (item) {
                return {
                  text: item.name,
                  id: item.id
                }
              })
            };
          }
        }
      });
    });
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>RailsAutocompleteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    $(document).ready(function() {
      $("#e11").select2({
        placeholder: "pesquisa...",
        minimumInputLength: 2,
        multiple: true,
        width: "300px",
        ajax: {
          url: "<%= user_name_search_path(format: 'json') %>",
          dataType: "json",
          data: function (term) {
            return {
              term: term
            };
          },
          results: function (data) {
            return {
              results: $.map(data, function (item) {
                return {
                  text: item.name,
                  id: item.id
                }
              })
            };
          }
        }
      });
    });
    $(document).ready(function() {
      $('#e111').select2({
        ajax: {
          url: "<%= users_path(format: 'json') %>",
          dataType: "json",
          placeholder: 'Informe os itens...',
          results: function(data, page) {
            return {
              results: $.map( data, function(user, i) {
                return { id: user.id, text: user.name }
              } )
            }
          }
        }
      });
    });
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
 <% if @user.errors.any? %>
 <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, id: "user_name" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <!--
  <input id="roles" type="hidden" value="<%#= @user.roles.pluck(:id).to_s.gsub(/[\[\]]/,'') %>" name="role_ids[]" width="300px"></input>
  -->

  <%= label_tag "Roles" %>
  <input id="userId" type="hidden" value="<%= @user.id %>"></input>
  <input id="roles" type="hidden" value="-" name="role_ids[]" width="300px"></input>
  </br></br>

 <div class="span8">
    <h3>Example Code</h3>
    <pre class="prettyprint linenums" id="code_e1"><ol class="linenums"><li class="L0"><span class="tag">&lt;head&gt;</span></li><li class="L3"><span class="pln"> </span><span class="tag">&lt;script&gt;</span></li><li class="L4"><span class="pln"> $</span><span class="pun">(</span><span class="pln">document</span><span class="pun">).</span><span class="pln">ready</span><span class="pun">(</span><span class="kwd">function</span><span class="pun">()</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> $</span><span class="pun">(</span><span class="str">"#e1"</span><span class="pun">).</span><span class="pln">select2</span><span class="pun">();</span><span class="pln"> </span><span class="pun">});</span></li><li class="L5"><span class="pln"> </span><span class="tag">&lt;/script&gt;</span></li><li class="L6"><span class="tag">&lt;/head&gt;</span></li><li class="L7"><span class="tag">&lt;body&gt;</span></li><li class="L8"><span class="pln"> </span><span class="tag">&lt;select</span><span class="pln"> </span><span class="atn">id</span><span class="pun">=</span><span class="atv">"e1"</span><span class="tag">&gt;</span></li><li class="L9"><span class="pln"> </span><span class="tag">&lt;option</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"AL"</span><span class="tag">&gt;</span><span class="pln">Alabama</span><span class="tag">&lt;/option&gt;</span></li><li class="L1"><span class="pln"> </span><span class="tag">&lt;option</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"WY"</span><span class="tag">&gt;</span><span class="pln">Wyoming</span><span class="tag">&lt;/option&gt;</span></li><li class="L2"><span class="pln"> </span><span class="tag">&lt;/select&gt;</span></li><li class="L3"><span class="tag">&lt;/body&gt;</span></li></ol></pre>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/old_form.html.erb
<%= form_for(@user) do |f| %>
 <% if @user.errors.any? %>
 <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <select id="ex", multiple="true" style="width:300px">¬
    <option value="MI">Miami</option>
    <option value="NY">New York</option>
    <option value="AL">Alabama</option>
    <option value="WY">Wyoming</option>
    <option value="AK">Alaska</option>
    <option value="CA">California</option>
  </select>¬

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, id: "user_name" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>


  <input type="hidden" id="e11" width="300px"></input>
  </br></br>


  <%= collection_select :user, :id,
    User.all, :id, :name,
    { :selected => @user.id },
    { :style => "width:300px", :id => "e12", :multiple => true, :name => 'user[user_ids][]' } %>

  <div class="span8">
    <h3>Example Code</h3>
    <pre class="prettyprint linenums" id="code_e1"><ol class="linenums"><li class="L0"><span class="tag">&lt;head&gt;</span></li><li class="L3"><span class="pln"> </span><span class="tag">&lt;script&gt;</span></li><li class="L4"><span class="pln"> $</span><span class="pun">(</span><span class="pln">document</span><span class="pun">).</span><span class="pln">ready</span><span class="pun">(</span><span class="kwd">function</span><span class="pun">()</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> $</span><span class="pun">(</span><span class="str">"#e1"</span><span class="pun">).</span><span class="pln">select2</span><span class="pun">();</span><span class="pln"> </span><span class="pun">});</span></li><li class="L5"><span class="pln"> </span><span class="tag">&lt;/script&gt;</span></li><li class="L6"><span class="tag">&lt;/head&gt;</span></li><li class="L7"><span class="tag">&lt;body&gt;</span></li><li class="L8"><span class="pln"> </span><span class="tag">&lt;select</span><span class="pln"> </span><span class="atn">id</span><span class="pun">=</span><span class="atv">"e1"</span><span class="tag">&gt;</span></li><li class="L9"><span class="pln"> </span><span class="tag">&lt;option</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"AL"</span><span class="tag">&gt;</span><span class="pln">Alabama</span><span class="tag">&lt;/option&gt;</span></li><li class="L1"><span class="pln"> </span><span class="tag">&lt;option</span><span class="pln"> </span><span class="atn">value</span><span class="pun">=</span><span class="atv">"WY"</span><span class="tag">&gt;</span><span class="pln">Wyoming</span><span class="tag">&lt;/option&gt;</span></li><li class="L2"><span class="pln"> </span><span class="tag">&lt;/select&gt;</span></li><li class="L3"><span class="tag">&lt;/body&gt;</span></li></ol></pre>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>